name: Build apk

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    env:
      ver: 1.20.3
      apkfile: bilibili-play
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: setup java runtime
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          java-package: 'jre'
      - name: Get files
        run: |
          echo Downloading vanilla apk
          wget https://github.com/luyanci/initial-biliroaming-maker/releases/download/vanlia/${ env.apkfile }.apk
          echo Downloading patches
          wget https://github.com/BiliRoamingX/BiliRoamingX/releases/download/v${ env.ver }/BiliRoamingX-patches-${ env.ver }.jar -O patches.jar
          wget https://github.com/BiliRoamingX/BiliRoamingX/releases/download/v${ env.ver }/BiliRoamingX-integrations-${ env.ver }.apk -Ointegrations.apk
          echo Downloading modified revanced-cli
          wget https://github.com/zjns/revanced-cli/releases/download/latest/revanced-cli.jar
      - name: Build Patched apk
        run: java -jar revanced-cli.jar patch --merge integrations.apk --patch-bundle patches.jar --signing-levels 2,3 { env.apkfile }.apk
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
